doveadm: client - Fix connecting to UNIX sockets that don't need authentication
Trying to access doveadm UNIX socket that didn't require authentication
failed with:

Error: doveadm server sent invalid handshake: ...