lib-index: When finding a view is reset, don't attempt any further syncing.
This could cause various errors to be logged, such as:
Error: Append with UID 7103, but next_uid = 7242