auth: db-ldap - Fix deleting wrong LDAP request when ldap_search() or ldap_bind() failed
This mainly means that if an invalid LDAP filter was used, wrong request
could have become deleted. Fixes:

Error: ldap(...): Reply with unknown msgid 2
Panic: file db-ldap.c: line 1343 (db_ldap_conn_close): assertion failed: (request->msgid != -1)