FIX dsync_remote_cmd: Remove obsolete and removed "-U" parameter
This PR intends to fix an error due to the default doveadm settings adding the obsolete and removed "-U" parameter to dsync.

The option "-U" was removed in commit 4c04e4c30fd (July 7, 2023) - "global: Remove replicator" removed.

The "-U" parameter in the doveadm_settings struct was probably overlooked and causes errors like this:

```
doveadm sync -1 -u name@domain.tld remote:sub.remote.tld
dsync-server: invalid option -- 'U'
Error: doveadm: Unexpected or incomplete option: -U
dsync-local(name@domain.tld)<I2I5HXkkC2mXLgwAXmhsDw>: Error: read(sub.remote.tld) failed: EOF (version not received)
dsync-local(name@domain.tld)<I2I5HXkkC2mXLgwAXmhsDw>: Error: cmd sync: Remote command returned error 64: ssh sub.remote.tld doveadm dsync-server -uname@domain.tld -U
```

See also: https://dovecot.org/mailman3/archives/list/dovecot@dovecot.org/message/B3TQFAHCYVVXXEL4Y7KOPKJRWZ5I6X7D/