mdbox: Fix rebuilding when dovecot.map.index is missing map/ref extension
The rebuild kept just repeatedly failing with:
Error: mdbox map .../dovecot.map.index corrupted: missing map extension